{
  "formatVersion": "1.1",
  "component": {
    "group": "net.yqloss",
    "module": "enchanted-java-library",
    "version": "0.16.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "enchanted-java-library-0.16.0.jar",
          "url": "enchanted-java-library-0.16.0.jar",
          "size": 4159,
          "sha512": "57ac3127caae86eb7b88feaaf4f75629fcf9d0fa37b2f480a94dd8801c7faff2f333a0c39e7374513940a3c06267e771c4b0b88f0a960640fb44f67156b25b7a",
          "sha256": "3155a6230760e206dd42531b8004a6517ac5182483f2851f80b08bb7d2970e4a",
          "sha1": "7da1ce1b6f135d0b074197c33ba8fdd8cd3cb79d",
          "md5": "654603a4eafc914ea09f23af8f1a101c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "enchanted-java-library-0.16.0.jar",
          "url": "enchanted-java-library-0.16.0.jar",
          "size": 4159,
          "sha512": "57ac3127caae86eb7b88feaaf4f75629fcf9d0fa37b2f480a94dd8801c7faff2f333a0c39e7374513940a3c06267e771c4b0b88f0a960640fb44f67156b25b7a",
          "sha256": "3155a6230760e206dd42531b8004a6517ac5182483f2851f80b08bb7d2970e4a",
          "sha1": "7da1ce1b6f135d0b074197c33ba8fdd8cd3cb79d",
          "md5": "654603a4eafc914ea09f23af8f1a101c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "enchanted-java-library-0.16.0-sources.jar",
          "url": "enchanted-java-library-0.16.0-sources.jar",
          "size": 14394,
          "sha512": "11cc04188fa26bcc4ea6eb8bb058fd37bc842482698a90579ed3120a9cb707e8e64dcd5edbfaec6e9b0b7e5c58357298704dc049aed43b8d543dd8da2ef1c2ef",
          "sha256": "00052bfb6d346cec49db1ec214d2d554495a5f94c290dd96e175bf3d63fde4d3",
          "sha1": "d23959b28ec925815c89fa9db2197ce0d4092b90",
          "md5": "118e011e9d24228d2839f31cb54b26cc"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "enchanted-java-library-0.16.0-javadoc.jar",
          "url": "enchanted-java-library-0.16.0-javadoc.jar",
          "size": 115408,
          "sha512": "39c1efe5c00b80be7f4f5b11ed8ffe5ddd3c8a4684cbed40d72c505a5560ab590aef1b56157b19b326a81fa1b428cca90cecb8556d145c0f2f766004685d3b37",
          "sha256": "98b307a5b183921232570191b23dae019b7b942268a807fdd2f4590637d9fd3d",
          "sha1": "a656838559b33090c813d9824173d626082147fe",
          "md5": "b2267d206fbaee8ac8b18bb5795fbf81"
        }
      ]
    }
  ]
}
